### PR TITLE
feat:add cart functionality

### PR DESCRIPTION
**Pull request by rahulmistry751**
Added Cart functionality
- Add to cart
- Remove from cart
- Move to wishlist
- Increase/decrease quantity
- Move to cart

### CODE REVIEW

**Review by ApurvaSawant11 — APPROVED** [review]
Everything looks good to me! UI also looks great. You can merge the PR

**Comment by Digambar1411** [comment]
UI looks great and clean.
only have one suggestion post adding particular product in cart you can toggle "add to cart " button to "go to cart" and user can directly go to cart by clicking the button.

**Review by Digambar1411 — APPROVED** [review]
left one suggestion rest looks good

**Comment by rahulmistry751** [comment]
> UI looks great and clean. only have one suggestion post adding particular product in cart you can toggle "add to cart " button to "go to cart" and user can directly go to cart by clicking the button.

Thanks for suggestion. Added go to cart functionality

**Pull request merged**
